name: CD

on:
  worflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  CD:
    name: Contiuous Delivery
    runs-on: ubuntu-latest

    if ${{ github.event.workflow_run.run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        action: actions/checkout@v3