name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed


jobs:
  CD:
    name: Contiuous Delivery
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3