name: CD

on:
  workflow_run:
    workflows: [CD]
    types:
      - completed


jobs:
  CD:
    name: Contiuous Delivery
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3